--- 
apiVersion: v1
kind: Pod
metadata: 
  name: test-pd
spec: 
  containers: 
    - 
      command: 
        - 
          sleep: ~
        - "100000"
      image: "centos:7"
      name: centos
      volumeMounts: 
        - 
          mountpath: /cache
          name: cache-volume
  volumes: 
    - 
      emptyDir: {}
      name: cache-volume
